spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: ILikeOJ123!

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

